let srcImg = 'assets/images/sp/'

export let monProducts = [
  {
    id: 4,
    name: 'tranh in',
    price: '100.000',
    priceFirst: '200.000',
    percent: 50,
    category: 'cờ',
    sizes: ['XS', 'M', 'XXL'],
    colors: ['orange', 'yellow', 'green'],
    des: '',
    imgs: [`4`],
  },
  {
    id: 3,
    name: 'bảng treo',
    price: '200.000',
    priceFirst: '400.000',
    percent: 50,
    category: 'cờ',
    sizes: ['S', 'M'],
    colors: ['white', 'blue', 'black'],
    des: '',
    imgs: [`3`],
  },
  {
    id: 2,
    name: 'cờ có đế',
    price: '300.000',
    priceFirst: '600.000',
    percent: 50,
    category: 'cờ',
    sizes: ['S', 'M', 'L'],
    colors: ['red', 'blue', 'green'],
    des: '',
    imgs: [`2`],
  },
  {
    id: 1,
    name: 'cờ trang trí nhật bản',
    price: '100.000',
    priceFirst: '200.000',
    percent: 50,
    category: 'cờ',
    sizes: ['S', 'M', 'L'],
    colors: ['red', 'blue', 'green'],
    des: '',
    imgs: [`1`, `1-1`, `1-2`],
  },
  {
    id: 0,
    name: 'daruma',
    price: '600.000',
    priceFirst: '1.200.000',
    percent: 50,
    category: 'daruma',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['red', 'yellow'],
    des: 'Daruma Nguyện Ước giấy truyền thống Nhật Bản, một thần vật bùa may mắn truyền thống của Nhật Bản mô phỏng theo Bồ Đề Đạt Ma, người sáng lập ra truyền thống Thiền tông của Phật giáo.',
    imgs: [`0`, `0-1`, `0-2`],
  },
]
